import { Miniflare } from 'miniflare';
import { readFileSync,readdirSync } from 'node:fs';
import assert from 'node:assert/strict';
const mf=new Miniflare({modules:[{type:'ESModule',path:'dist/server/index.js'},...readdirSync('dist/server',{recursive:true}).filter(f=>/\.m?js$/.test(f)&&f!=='index.js').map(f=>({type:'ESModule',path:'dist/server/'+f}))],modulesRoot:'dist/server',compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:{DB:'test-db'},r2Buckets:['BUCKET'],assets:{directory:'dist/client',binding:'ASSETS',routerConfig:{has_user_worker:true,invoke_user_worker_ahead_of_assets:true}},logRequests:false});
const passed=[],failed=[];
async function test(name,fn){try{await fn();passed.push(name);console.log('PASS',name)}catch(e){failed.push({name,error:e.message});console.error('FAIL',name,e.message)}}
const config={name:'Projeto de teste',objective:'Produto',description:'Bota preta em bancada de madeira',action:'Fotografia frontal',camera:'50 mm · altura dos olhos',lighting:'Luz natural suave',style:'Ultrarrealista',ratio:'9:16',language:'Português',preserve:true,memory:''};
const identity=(user='test-a')=>({'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.test'});
async function request(path,{user='test-a',method='GET',body,raw,headers={}}={}){const r=await mf.dispatchFetch('http://localhost'+path,{method,headers:{...(user?identity(user):{}),...(body||raw?{'Content-Type':'application/json'}:{}),...headers},body:body?JSON.stringify(body):raw});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data=text}return {status:r.status,data,headers:r.headers};}
let image,generated,project;
try{
 const db=await mf.getD1Database('DB');for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort()){for(const stmt of readFileSync('drizzle/'+file,'utf8').split('--> statement-breakpoint'))if(stmt.trim())await db.prepare(stmt.trim()).run();}
 await test('Página principal renderiza no Worker',async()=>{const r=await request('/');assert.equal(r.status,200);assert.match(r.data,/Ideias ganham forma aqui/)});
 await test('API exige autenticação',async()=>{const r=await request('/api/projects',{user:null});assert.equal(r.status,401)});
 await test('Estado da IA sem chave',async()=>{const r=await request('/api/status');assert.equal(r.status,200);assert.equal(r.data.ai,false)});
 await test('Upload PNG e leitura dos bytes',async()=>{const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a/p8AAAAASUVORK5CYII=','base64');const f=new FormData();f.append('file',new File([png],'test.png',{type:'image/png'}));const encoded=new Request('http://localhost/api/upload',{method:'POST',body:f});const r=await mf.dispatchFetch(encoded.url,{method:'POST',headers:{...identity(),'Content-Type':encoded.headers.get('content-type')},body:await encoded.arrayBuffer()});image=await r.json();assert.equal(r.status,200);const read=await mf.dispatchFetch('http://localhost'+image.url,{headers:identity()});assert.equal(read.status,200);assert.deepEqual(Buffer.from(await read.arrayBuffer()),png)});
 await test('Imagem privada entre usuários',async()=>{assert.equal((await request(image.url,{user:'test-b'})).status,404)});
 await test('Composição de prompt',async()=>{const r=await request('/api/generate-prompt',{method:'POST',body:{config,imageId:image.id}});assert.equal(r.status,200);assert.match(r.data.prompt,/Bota preta/);generated=r.data});
 await test('Salvar e reabrir projeto',async()=>{const r=await request('/api/save-prompt',{method:'POST',body:{name:config.name,objective:config.objective,config,imageId:image.id,...generated}});assert.equal(r.status,200);project=r.data;const list=await request('/api/projects');assert.equal(list.data.length,1);assert.deepEqual(JSON.parse(list.data[0].config),config);assert.equal(list.data[0].prompt,generated.prompt)});
 await test('Projetos privados entre usuários',async()=>{assert.deepEqual((await request('/api/projects',{user:'test-b'})).data,[])});
 await test('Salvar e listar memória',async()=>{const r=await request('/api/memories',{method:'POST',body:{kind:'character',name:'Personagem de teste',details:'Cabelo curto e camiseta azul'}});assert.equal(r.status,200);assert.equal((await request('/api/memories')).data.length,1);assert.deepEqual((await request('/api/memories',{user:'test-b'})).data,[])});
 await test('Recusa referência de outro usuário',async()=>{const r=await request('/api/save-prompt',{user:'test-b',method:'POST',body:{name:'Teste',prompt:'Texto',config,imageId:image.id}});assert.equal(r.status,404)});
 await test('Recusa origem externa',async()=>{const r=await request('/api/generate-prompt',{method:'POST',body:{config},headers:{origin:'https://example.net'}});assert.equal(r.status,403)});
 await test('Descrição vazia é recusada',async()=>{const r=await request('/api/generate-prompt',{method:'POST',body:{config:{...config,description:''}}});assert.equal(r.status,400)});
 await test('JSON inválido retorna erro de entrada',async()=>{const r=await request('/api/save-prompt',{method:'POST',raw:'{bad'});assert.equal(r.status,400)});
 await test('Configuração longa preservada sem truncamento',async()=>{const long={...config,description:'"'.repeat(7900),action:'b'.repeat(7900),memory:'c'.repeat(7900)};const r=await request('/api/save-prompt',{method:'POST',body:{name:'Longo',prompt:'Prompt válido',config:long}});assert.equal(r.status,200);const list=await request('/api/projects');assert.deepEqual(JSON.parse(list.data.find(p=>p.id===r.data.id).config),long)});
 await test('Arquivo com assinatura incompleta é recusado',async()=>{const f=new FormData();f.append('file',new File([new Uint8Array([137,80,78])],'fake.png',{type:'image/png'}));const encoded=new Request('http://localhost/api/upload',{method:'POST',body:f});const r=await mf.dispatchFetch(encoded.url,{method:'POST',headers:{...identity(),'Content-Type':encoded.headers.get('content-type')},body:await encoded.arrayBuffer()});assert.equal(r.status,400)});
 await test('Memória vazia é recusada',async()=>{assert.equal((await request('/api/memories',{method:'POST',body:{kind:'product',name:' ',details:' '}})).status,400)});
 await test('Configuração com formato desconhecido é recusada',async()=>{assert.equal((await request('/api/generate-prompt',{method:'POST',body:{config:{...config,ratio:'banana'}}})).status,400)});
 await test('Composição não aceita imagem de outro usuário',async()=>{assert.equal((await request('/api/generate-prompt',{user:'test-b',method:'POST',body:{config,imageId:image.id}})).status,404)});
 await test('Objeto nulo é recusado',async()=>{assert.equal((await request('/api/save-prompt',{method:'POST',raw:'null'})).status,400)});
 await test('Nome excessivo é recusado sem cortar dados',async()=>{assert.equal((await request('/api/save-prompt',{method:'POST',body:{name:'a'.repeat(121),prompt:'Teste',config}})).status,400)});
 await test('Gravações exigem autenticação',async()=>{for(const path of ['save-prompt','memories','generate-prompt','analyze-image','upload'])assert.equal((await request('/api/'+path,{user:null,method:'POST',body:{config}})).status,401)});
 await test('JSON acima do limite é recusado',async()=>{assert.equal((await request('/api/save-prompt',{method:'POST',body:{name:'Grande',prompt:'a'.repeat(300000),config}})).status,413)});
 await test('Projeto com regras negativas longas preserva texto',async()=>{const negative='n'.repeat(7000);const r=await request('/api/save-prompt',{method:'POST',body:{name:'Regras longas',prompt:'Teste',negative,config}});assert.equal(r.status,200);assert.equal((await request('/api/projects')).data.find(p=>p.id===r.data.id).negative,negative)});
 for(const [extension,mime] of [['jpg','image/jpeg'],['webp','image/webp']])await test('Upload e leitura de '+extension.toUpperCase(),async()=>{const bytes=readFileSync('tests/fixtures/reference.'+extension);const f=new FormData();f.append('file',new File([bytes],'reference.'+extension,{type:mime}));const encoded=new Request('http://localhost/api/upload',{method:'POST',body:f});const r=await mf.dispatchFetch(encoded.url,{method:'POST',headers:{...identity(),'Content-Type':encoded.headers.get('content-type')},body:await encoded.arrayBuffer()});assert.equal(r.status,200);const saved=await r.json();const read=await mf.dispatchFetch('http://localhost'+saved.url,{headers:identity()});assert.equal(read.headers.get('content-type'),mime);assert.deepEqual(Buffer.from(await read.arrayBuffer()),bytes)});
 await test('Seis objetivos e dois idiomas de estrutura',async()=>{for(const objective of ['Vídeo Veo','TikTok Shop','Foto Instagram','Produto','Personagem','Cinema'])for(const language of ['English','Português']){const r=await request('/api/generate-prompt',{method:'POST',body:{config:{...config,objective,language}}});assert.equal(r.status,200);assert.ok(r.data.prompt.includes('9:16'));assert.ok(r.data.negative);assert.equal(Boolean(r.data.script),objective==='TikTok Shop');assert.ok(!r.data.prompt.includes('attached reference image'));assert.ok(!r.data.prompt.includes('referência anexada'))}});
 await test('Arquivo maior que 10 MB é recusado',async()=>{const f=new FormData();f.append('file',new File([new Uint8Array(10*1024*1024+1)],'large.png',{type:'image/png'}));const encoded=new Request('http://localhost/api/upload',{method:'POST',body:f});const r=await mf.dispatchFetch(encoded.url,{method:'POST',headers:{...identity(),'Content-Type':encoded.headers.get('content-type')},body:await encoded.arrayBuffer()});assert.ok([400,413].includes(r.status))});
 await test('Análise sem provedor retorna indisponibilidade clara',async()=>{const r=await request('/api/analyze-image',{method:'POST',body:{imageId:image.id}});assert.equal(r.status,503)});
}finally{await mf.dispose();console.log(JSON.stringify({passed:passed.length,failed},null,2));if(failed.length)process.exitCode=1;}
