'use client';
import { useState,useEffect,useRef, type ReactNode } from 'react';
import { Sparkles,LayoutDashboard,FolderOpen,Library,Users,Package,History,Settings,Plus,Upload,Image as ImageIcon,Video,Camera,Clapperboard,ShoppingBag,Copy,Check,Save,SlidersHorizontal,ScanLine,ShieldCheck,Layers,Zap,Search,ChevronRight,X,Loader2,BookOpen,MonitorPlay,Download,LogIn } from 'lucide-react';
import { SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarGroup,SidebarGroupLabel,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,useSidebar } from '@/components/ui/sidebar';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Switch } from '@/components/ui/switch';
import { Skeleton } from '@/components/ui/skeleton';
import { Empty,EmptyHeader,EmptyTitle,EmptyDescription,EmptyMedia } from '@/components/ui/empty';
import { Toaster,toast } from 'sonner';
import { initialConfig,templates,objectives,type Config } from '@/lib/prompt';
type View='Dashboard'|'Criar prompt'|'Projetos'|'Biblioteca'|'Personagens'|'Produtos'|'Histórico'|'Configurações';
type Project={id:string;name:string;objective:string;image_id:string|null;config:string;prompt:string;negative:string;script:string;created_at:string};
type Memory={id:string;kind:string;name:string;details:string};
type Result={prompt:string;negative:string;script:string};
const nav=[{label:'Dashboard',icon:LayoutDashboard},{label:'Criar prompt',icon:Sparkles},{label:'Projetos',icon:FolderOpen},{label:'Biblioteca',icon:Library},{label:'Personagens',icon:Users},{label:'Produtos',icon:Package},{label:'Histórico',icon:History}] as const;
const goalIcons=[Video,ShoppingBag,Camera,Package,Users,Clapperboard];
async function api<T=any>(path:string,body?:unknown):Promise<T>{const resp=await fetch('/api/'+path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const data:any=await resp.json();if(!resp.ok)throw new Error(data.error||'Não foi possível concluir.');return data;}
function Picker({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:string)=>void}){return <label className="field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger className="picker"><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o} value={o}>{o}</SelectItem>)}</SelectContent></Select></label>}
function Blank({title,description,icon:Icon=FolderOpen}:{title:string;description:string;icon?:typeof FolderOpen}){return <Empty className="empty-box"><EmptyHeader><EmptyMedia variant="icon"><Icon/></EmptyMedia><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{description}</EmptyDescription></EmptyHeader></Empty>}
function NavButton({label,Icon,current,onGo}:{label:View;Icon:typeof Sparkles;current:View;onGo:(v:View)=>void}){const {setOpenMobile}=useSidebar();return <SidebarMenuItem><SidebarMenuButton className="nav-button" isActive={current===label} onClick={()=>{onGo(label);setOpenMobile(false)}}><Icon/><span>{label}</span>{label==='Criar prompt'&&<span className="nav-new">NOVO</span>}</SidebarMenuButton></SidebarMenuItem>}
export default function Studio({user}:{user:{name:string;email:string}|null}){
 const [view,setView]=useState<View>('Dashboard'),[config,setConfig]=useState<Config>(initialConfig),[image,setImage]=useState<{id:string;url:string;name:string}|null>(null),[result,setResult]=useState<Result|null>(null),[projects,setProjects]=useState<Project[]>([]),[memories,setMemories]=useState<Memory[]>([]),[busy,setBusy]=useState(''),[loading,setLoading]=useState(!!user),[loadError,setLoadError]=useState(''),[search,setSearch]=useState(''),[ai,setAi]=useState(false),[dragging,setDragging]=useState(false),[modal,setModal]=useState<'memory'|'help'|'plans'|null>(null),[memoryKind,setMemoryKind]=useState('character'),[memoryName,setMemoryName]=useState(''),[memoryDetails,setMemoryDetails]=useState(''),[tab,setTab]=useState('prompt'),[saved,setSaved]=useState(false),[analysis,setAnalysis]=useState<Record<string,string>|null>(null);
 const inputRef=useRef<HTMLInputElement>(null),resultRef=useRef<HTMLDivElement>(null);
 const update=(key:keyof Config,value:string|boolean)=>{setConfig(c=>({...c,[key]:value}));setSaved(false)};
 async function refresh(){if(!user){setLoading(false);return;}try{setLoadError('');const [p,m,s]=await Promise.all([api('projects'),api('memories'),api('status')]);setProjects(p);setMemories(m);setAi(s.ai);}catch(e){setLoadError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void refresh()},[]);
 useEffect(()=>{const mc=(document as any).modelContext;if(!mc?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(mc.registerTool({name:'stage_prompt_brief',title:'Preparar briefing do prompt',description:'Preenche o briefing e abre o editor. Não gera nem salva o projeto.',inputSchema:{type:'object',properties:{description:{type:'string'},objective:{type:'string',enum:objectives}},required:['description'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input:unknown){const v=input as {description?:string;objective?:string};if(!v||typeof v.description!=='string'||!v.description.trim()||v.description.length>8000||(v.objective&&!objectives.includes(v.objective)))throw new Error('Briefing inválido');setConfig(c=>({...c,description:v.description!,objective:v.objective||c.objective}));setView('Criar prompt');setSaved(false);return {staged:true,objective:v.objective||'mantido'};}},{signal:lifecycle.signal})).catch(()=>{});return ()=>lifecycle.abort()},[]);
 const requireUser=()=>{if(user)return true;toast.error('Entre com ChatGPT para enviar e salvar seus projetos.');return false};
 async function upload(file?:File){if(!file||busy||!requireUser())return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){toast.error('Envie PNG, JPG ou WebP de até 10 MB.');return;}setBusy('upload');try{const form=new FormData();form.append('file',file);const r=await fetch('/api/upload',{method:'POST',body:form});const d:any=await r.json();if(!r.ok)throw new Error(d.error);setImage(d);setAnalysis(null);setResult(null);setSaved(false);toast.success('Referência enviada.');}catch(e){toast.error((e as Error).message)}finally{setBusy('');if(inputRef.current)inputRef.current.value=''}}
 async function analyze(){if(!image||!requireUser())return;setBusy('analysis');try{const a=await api('analyze-image',{imageId:image.id});setAnalysis(a);setConfig(c=>({...c,description:a.description}));toast.success('Análise pronta. Revise a descrição antes de gerar.')}catch(e){toast.error((e as Error).message)}finally{setBusy('')}}
 async function generate(){if(!requireUser())return;if(!config.description.trim()){toast.error('Descreva a referência ou a cena desejada.');document.getElementById('description')?.focus();return}setBusy('generate');try{const r=await api('generate-prompt',{config,imageId:image?.id});setResult(r);setSaved(false);setTab('prompt');setTimeout(()=>resultRef.current?.scrollIntoView({behavior:'smooth',block:'start'}),80);}catch(e){toast.error((e as Error).message)}finally{setBusy('')}}
 async function save(){if(!result||!requireUser())return;if(!config.name.trim()){toast.error('Dê um nome ao projeto antes de salvar.');document.getElementById('project-name')?.focus();return;}setBusy('save');try{await api('save-prompt',{...result,...config,config,imageId:image?.id});setSaved(true);await refresh();toast.success('Projeto salvo no histórico.')}catch(e){toast.error((e as Error).message)}finally{setBusy('')}}
 async function copy(){if(!result)return;try{await navigator.clipboard.writeText(tab==='negative'?result.negative:tab==='script'?result.script:result.prompt);toast.success('Copiado para a área de transferência.')}catch{toast.error('Selecione o texto para copiar manualmente.')}}
 function useTemplate(t:typeof templates[number]){setConfig(c=>({...c,...t.config}));setView('Criar prompt');setResult(null);setSaved(false);toast.success('Modelo aplicado. Adicione sua descrição.');}
 function openProject(p:Project){try{setConfig({...initialConfig,...JSON.parse(p.config),name:p.name});setResult({prompt:p.prompt,negative:p.negative,script:p.script});setImage(p.image_id?{id:p.image_id,url:'/api/image/'+p.image_id,name:'Referência do projeto'}:null);setView('Criar prompt');setSaved(true);setAnalysis(null);setTab('prompt')}catch{toast.error('Não foi possível abrir esse projeto.')}}
 function newProject(){setConfig(initialConfig);setImage(null);setResult(null);setAnalysis(null);setSaved(false);setView('Criar prompt');}
 async function saveMemory(){if(!requireUser())return;setBusy('memory');try{await api('memories',{kind:memoryKind,name:memoryName,details:memoryDetails});await refresh();setModal(null);setMemoryName('');setMemoryDetails('');toast.success('Referência salva na biblioteca.')}catch(e){toast.error((e as Error).message)}finally{setBusy('')}}
 const filtered=projects.filter(p=>(p.name+' '+p.objective).toLowerCase().includes(search.toLowerCase()));
 return <SidebarProvider style={{'--sidebar-width':'248px'} as React.CSSProperties}><Toaster theme="dark" position="bottom-right" richColors/><Sidebar className="studio-sidebar"><SidebarHeader className="brand-wrap"><button className="brand" onClick={()=>setView('Dashboard')}><span className="brand-mark"><Layers size={23}/></span><span>PROMPT<span className="brand-sub">AI STUDIO</span></span></button><div className="workspace-label"><span className="workspace-icon">K</span><span>Meu espaço criativo<small>Workspace pessoal</small></span></div></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel className="section-label">ESTÚDIO</SidebarGroupLabel><SidebarMenu>{nav.map(n=><NavButton key={n.label} label={n.label} Icon={n.icon} current={view} onGo={setView}/>)}</SidebarMenu></SidebarGroup><SidebarGroup className="sidebar-bottom"><div className="sidebar-note"><div><Zap size={17}/> Mais espaço para criar</div><p>Conheça a evolução do seu estúdio.</p><button onClick={()=>setModal('plans')}>Explorar planos</button></div></SidebarGroup></SidebarContent><SidebarFooter className="account-footer"><SidebarMenu><NavButton label="Configurações" Icon={Settings} current={view} onGo={setView}/></SidebarMenu><div className="account"><span className="avatar">{user?user.name.slice(0,1).toUpperCase():'K'}</span><span>{user?user.name:'Seu workspace'}<small>{user?'Acesso privado':'Entre para salvar'}</small></span><ShieldCheck size={17}/></div></SidebarFooter></Sidebar>
 <main className="studio-main"><header className="topbar"><div className="breadcrumb"><SidebarTrigger className="mobile-menu"/><span>Workspace</span><ChevronRight size={14}/><strong>{view}</strong></div><div className="top-actions"><span className="version-badge">BETA 1.0</span><button className="text-button help-button" onClick={()=>setModal('help')}><BookOpen size={16}/>Guia rápido</button><span className="top-avatar">{user?user.name.slice(0,1).toUpperCase():'K'}</span></div></header>
 <div className="page-content">
 {!user&&<div className="signin-banner"><div><LogIn size={18}/><span>Seu estúdio está pronto. Entre para criar e salvar projetos.</span></div><a href="/signin-with-chatgpt?return_to=%2F" target="_top">Entrar com ChatGPT</a></div>}
 {loadError&&<div className="error-banner">{loadError}<button onClick={()=>void refresh()}>Tentar novamente</button></div>}
 {(view==='Dashboard'||view==='Criar prompt')&&<>
 <div className="page-heading"><div><div className="eyebrow">SEU ESTÚDIO, SUAS POSSIBILIDADES</div><h1>{view==='Dashboard'?'Ideias ganham forma aqui.':'Vamos criar algo incrível.'}</h1><p>Transforme suas referências em prompts prontos para criar.</p></div><button className="secondary-button" onClick={()=>setView('Biblioteca')}><Library size={17}/>Explorar modelos</button></div>
 <div className="workflow"><span className="step active"><b>01</b> Adicione uma referência</span><span className="workflow-line"/><span className={'step '+(config.description?'active':'')}><b>02</b> Defina sua visão</span><span className="workflow-line"/><span className={'step '+(result?'active':'')}><b>03</b> Crie seu prompt</span><span className="workflow-end"><Sparkles size={14}/> Do conceito à criação</span></div>
 <div className="creator-grid"><section className="panel reference-panel"><div className="panel-title"><div><span className="icon-square"><ImageIcon size={19}/></span><h2>Sua referência visual</h2></div><span className="small-label">OPCIONAL</span></div>
 <input ref={inputRef} id="image-upload" type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={e=>void upload(e.target.files?.[0])}/>
 <div className={'upload-zone '+(dragging?'dragging ':'')+(image?'has-image':'')} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);void upload(e.dataTransfer.files[0])}}>{image?<><img src={image.url} alt="Referência visual enviada"/><button className="remove-image" aria-label="Remover referência do projeto" onClick={()=>{setImage(null);setAnalysis(null);setSaved(false)}}><X size={16}/></button><button className="image-change" onClick={()=>inputRef.current?.click()}>Trocar imagem</button></>:<><div className="upload-symbol"><Upload size={29}/></div><h3>{busy==='upload'?'Enviando sua referência…':'Toda grande ideia tem um começo.'}</h3><p>Arraste sua imagem até aqui ou<br/>escolha uma referência do seu dispositivo.</p><button className="upload-button" disabled={!!busy} onClick={()=>inputRef.current?.click()}>{busy==='upload'?<Loader2 className="spin" size={17}/>:<Plus size={17}/>}Escolher imagem</button><small>JPG, PNG ou WebP • até 10 MB</small></>}</div>
 <div className="reference-foot"><ShieldCheck size={15}/><span>Suas referências ficam no seu espaço privado.</span></div>
 <div className="vision-box"><div className="vision-heading"><span><ScanLine size={18}/> Vision Analyzer</span><span className={'status-tag '+(ai?'available':'')}>{ai?'Conectado':'Conexão pendente'}</span></div><p>{ai?'Identifique sujeito, cenário e iluminação da imagem.':'Adicione uma descrição manual para começar. A análise automática precisa de conexão com IA.'}</p><button className="secondary-button full-width" disabled={!image||!ai||!!busy} onClick={()=>void analyze()}>{busy==='analysis'?<Loader2 size={16} className="spin"/>:<ScanLine size={16}/>}Analisar referência</button></div>
 {analysis&&<div className="analysis-result"><h3>Análise da referência</h3>{Object.entries(analysis).filter(([k])=>k!=='description').map(([k,v])=><p key={k}><strong>{({person:'Pessoa',clothing:'Roupa',product:'Produto',scene:'Cenário',lighting:'Luz',camera:'Câmera'} as Record<string,string>)[k]||k}:</strong> {String(v)}</p>)}</div>}
 </section>
 <section className="panel settings-panel"><div className="panel-title"><div><span className="icon-square"><SlidersHorizontal size={19}/></span><h2>Direção criativa</h2></div><span className="small-label">SEU CONTROLE</span></div><label className="field"><span>Nome do projeto</span><input id="project-name" value={config.name} maxLength={120} placeholder="Ex.: Campanha de verão" onChange={e=>update('name',e.target.value)}/></label>
 <div className="field"><span>O que você quer criar?</span><div className="objectives">{objectives.map((g,i)=>{const Icon=goalIcons[i];return <button key={g} className={config.objective===g?'selected':''} onClick={()=>update('objective',g)} aria-pressed={config.objective===g}><Icon size={17}/>{g}</button>})}</div></div>
 <label className="field"><span>Sujeito e cenário <span className="required">*</span></span><textarea id="description" maxLength={8000} value={config.description} onChange={e=>update('description',e.target.value)} placeholder="Descreva quem ou o que aparece, as cores, os materiais e o ambiente que você imagina…" rows={3}/></label>
 <div className="field-grid"><Picker label="Estilo visual" value={config.style} options={['Ultrarrealista','Cinematográfico','UGC natural','Fotografia editorial']} onChange={v=>update('style',v)}/><Picker label="Formato" value={config.ratio} options={['9:16','16:9','1:1','4:5']} onChange={v=>update('ratio',v)}/></div>
 <div className="field-grid"><Picker label="Câmera" value={config.camera} options={['50 mm · altura dos olhos','35 mm · travelling suave','85 mm · close nos detalhes','iPhone · enquadramento próximo']} onChange={v=>update('camera',v)}/><Picker label="Iluminação" value={config.lighting} options={['Luz natural suave','Luz lateral cinematográfica','Estúdio difuso','Golden hour']} onChange={v=>update('lighting',v)}/></div>
 <details className="advanced"><summary>Mais opções <Plus size={15}/></summary><label className="field"><span>Ação e movimento</span><textarea rows={2} value={config.action} maxLength={8000} onChange={e=>update('action',e.target.value)}/></label><Picker label="Idioma da estrutura" value={config.language} options={['English','Português']} onChange={v=>update('language',v)}/><p className="fine-print">Descrições e ações personalizadas são mantidas no idioma digitado.</p>{memories.length>0&&<label className="field"><span>Aplicar memória</span><Select value={memories.find(m=>m.name+': '+m.details===config.memory)?.id||(config.memory?'saved':'none')} onValueChange={id=>{const m=memories.find(v=>v.id===id);update('memory',m?m.name+': '+m.details:'')}}><SelectTrigger className="picker"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Nenhuma</SelectItem>{config.memory&&!memories.some(m=>m.name+': '+m.details===config.memory)&&<SelectItem value="saved">Referência do projeto</SelectItem>}{memories.map(m=><SelectItem key={m.id} value={m.id}>{m.name}</SelectItem>)}</SelectContent></Select></label>}</details>
 <div className="preserve-row"><ShieldCheck size={18}/><label htmlFor="preserve">Preservar identidade e detalhes<small>Regras de fidelidade incluídas no prompt</small></label><Switch id="preserve" checked={config.preserve} onCheckedChange={v=>update('preserve',v)}/></div>
 <button className="primary-button generate-button" disabled={!!busy} onClick={()=>void generate()}>{busy==='generate'?<Loader2 className="spin" size={19}/>:<Sparkles size={19}/>}Montar meu prompt<span className="button-tag">STUDIO</span></button><p className="generation-note">Composição por modelos • Sem consumo de créditos</p>
 </section></div>
 {result&&<section className="panel result-panel" ref={resultRef}><div className="panel-title"><div><span className="icon-square"><Sparkles size={19}/></span><h2>Seu prompt está pronto</h2></div><span className="status-tag">Editável</span></div><Tabs value={tab} onValueChange={setTab}><TabsList><TabsTrigger value="prompt">Prompt principal</TabsTrigger><TabsTrigger value="negative">Regras negativas</TabsTrigger>{result.script&&<TabsTrigger value="script">Roteiro</TabsTrigger>}</TabsList>{(['prompt','negative','script'] as const).filter(k=>k!=='script'||result.script).map(k=><TabsContent key={k} value={k}><textarea aria-label={k==='prompt'?'Prompt principal':k==='negative'?'Regras negativas':'Roteiro'} className="prompt-output" value={result[k]} onChange={e=>{setResult({...result,[k]:e.target.value});setSaved(false)}}/></TabsContent>)}</Tabs><div className="result-footer"><span><Check size={15}/> Revise o texto e anexe a referência na IA de destino.</span><div><button className="secondary-button" onClick={()=>void copy()}><Copy size={16}/>Copiar</button><button className="primary-button" disabled={!!busy||saved} onClick={()=>void save()}>{saved?<Check size={16}/>:<Save size={16}/>} {saved?'Salvo':'Salvar projeto'}</button></div></div></section>}
 <div className="section-heading"><div><h2>Um ponto de partida para cada ideia</h2><p>Escolha um modelo e dê o seu toque.</p></div><button className="text-button" onClick={()=>setView('Biblioteca')}>Ver biblioteca</button></div><div className="template-grid">{templates.slice(0,3).map((t,i)=>{const Icon=[ShoppingBag,Clapperboard,Package][i];return <button className={'template-card template-'+i} key={t.id} onClick={()=>useTemplate(t)}><div className="template-top"><span className="template-icon"><Icon size={23}/></span><span className="template-label">{t.category}</span></div><h3>{t.name}</h3><p>{t.description}</p><span className="template-use">Usar modelo <Plus size={15}/></span></button>})}</div>
 </>}
 {(view==='Projetos'||view==='Histórico')&&<><div className="page-heading"><div><div className="eyebrow">SEU PROCESSO CRIATIVO</div><h1>{view==='Projetos'?'Projetos que ganham vida.':'Cada ideia, no seu tempo.'}</h1><p>{projects.length} {projects.length===1?'projeto salvo':'projetos salvos'} no seu espaço.</p></div><button className="primary-button" onClick={newProject}><Plus size={17}/>Novo projeto</button></div><label className="search-field"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por nome ou objetivo"/></label>{loading?<div className="project-grid">{[1,2,3].map(i=><Skeleton key={i} className="h-56 rounded-xl"/>)}</div>:filtered.length?<div className="project-grid">{filtered.map(p=><button className="project-card" key={p.id} onClick={()=>openProject(p)}><div className="project-image">{p.image_id?<img src={'/api/image/'+p.image_id} alt={p.name}/>:<div className="project-no-image"><Sparkles size={40}/><span>{p.objective}</span></div>}</div><div className="project-info"><span className="template-label">{p.objective}</span><h3>{p.name}</h3><p>{new Date(p.created_at).toLocaleDateString('pt-BR',{day:'numeric',month:'long',year:'numeric'})}</p></div></button>)}</div>:<Blank title={search?'Nenhum resultado':'Sua próxima criação começa agora'} description={search?'Tente outro nome ou objetivo.':'Monte seu primeiro prompt e salve o projeto. Ele ficará disponível aqui.'}/>}</>}
 {view==='Biblioteca'&&<><div className="page-heading"><div><div className="eyebrow">MENOS PÁGINA EM BRANCO</div><h1>Biblioteca criativa.</h1><p>Direções prontas para adaptar à sua próxima ideia.</p></div></div><div className="template-grid library-grid">{templates.map((t,i)=>{const Icon=[ShoppingBag,Clapperboard,Package,Users][i];return <button key={t.id} className={'template-card template-'+i%3} onClick={()=>useTemplate(t)}><div className="template-top"><span className="template-icon"><Icon size={25}/></span><span className="template-label">{t.category}</span></div><h3>{t.name}</h3><p>{t.description}</p><span className="template-use">Aplicar no editor <Plus size={16}/></span></button>})}</div><div className="section-heading"><div><h2>Sua memória criativa</h2><p>Personagens e produtos que você quer preservar.</p></div></div><div className="memory-shortcuts"><button className="panel" onClick={()=>setView('Personagens')}><Users/><div><h3>Personagens</h3><p>{memories.filter(m=>m.kind==='character').length} referências salvas</p></div></button><button className="panel" onClick={()=>setView('Produtos')}><Package/><div><h3>Produtos</h3><p>{memories.filter(m=>m.kind==='product').length} referências salvas</p></div></button></div></>}
 {(view==='Personagens'||view==='Produtos')&&<><div className="page-heading"><div><div className="eyebrow">CONSISTÊNCIA EM CADA CRIAÇÃO</div><h1>{view==='Personagens'?'Personagens memoráveis.':'Cada detalhe importa.'}</h1><p>{view==='Personagens'?'Guarde identidade, cabelo, estilo e características.':'Guarde cores, materiais, textura e regras de preservação.'}</p></div><button className="primary-button" onClick={()=>{setMemoryKind(view==='Personagens'?'character':'product');setModal('memory')}}><Plus size={17}/>Nova referência</button></div>{memories.filter(m=>m.kind===(view==='Personagens'?'character':'product')).length?<div className="memory-grid">{memories.filter(m=>m.kind===(view==='Personagens'?'character':'product')).map(m=><div className="panel memory-card" key={m.id}><span className="icon-square">{m.kind==='character'?<Users/>:<Package/>}</span><h2>{m.name}</h2><p>{m.details}</p><button className="secondary-button" onClick={()=>{update('memory',m.name+': '+m.details);setView('Criar prompt');toast.success('Referência aplicada às opções do prompt.')}}>Usar no prompt</button></div>)}</div>:<Blank title="Uma boa referência merece ser lembrada" description="Adicione características fixas para reutilizar nos próximos prompts." icon={view==='Personagens'?Users:Package}/>}</>}
 {view==='Configurações'&&<><div className="page-heading"><div><div className="eyebrow">DO SEU JEITO</div><h1>Seu estúdio, organizado.</h1><p>Conta, conexões e estado da plataforma.</p></div></div><div className="settings-list"><section className="panel"><h2>Sua conta</h2><p>{user?.email||'Você ainda não entrou.'}</p>{user?<a className="secondary-button inline-flex" href="/signout-with-chatgpt?return_to=%2F" target="_top">Sair da conta</a>:<a className="primary-button inline-flex" href="/signin-with-chatgpt?return_to=%2F" target="_top">Entrar com ChatGPT</a>}</section><section className="panel"><div className="vision-heading"><h2>Análise visual com IA</h2><span className="status-tag">{ai?'Conectada':'Pendente'}</span></div><p>A análise automática precisa de um provedor de IA configurado para este estúdio. Enquanto isso, use a descrição manual e a composição por modelos.</p><p className="fine-print">A conexão é feita pelo responsável pelo site. Nenhuma chave é solicitada ou armazenada no navegador.</p></section><section className="panel"><h2>Planos e créditos</h2><p>Esta versão permite organizar referências e montar prompts sem cobrança. Assinaturas, créditos pagos e espaços de equipe ainda não estão ativados.</p><button className="secondary-button" onClick={()=>setModal('plans')}>Ver planos previstos</button></section></div></>}
 <footer className="page-footer"><span className="footer-brand"><Layers size={14}/> PROMPT AI STUDIO</span><span>Feito para dar forma à sua criatividade.</span><span>Versão inicial</span></footer>
 </div></main>
 <Dialog open={modal!==null} onOpenChange={open=>{if(!open)setModal(null)}}><DialogContent className="studio-dialog"><DialogHeader><DialogTitle>{modal==='memory'?'Nova referência criativa':modal==='help'?'Da referência à criação':'O próximo capítulo do seu estúdio'}</DialogTitle><DialogDescription>{modal==='memory'?'Descreva os detalhes que devem permanecer consistentes.':modal==='help'?'Seu fluxo em três passos simples.':'Planos previstos no projeto. Contratação ainda indisponível.'}</DialogDescription></DialogHeader>{modal==='memory'?<><label className="field"><span>Nome</span><input value={memoryName} maxLength={100} onChange={e=>setMemoryName(e.target.value)} placeholder={memoryKind==='character'?'Nome do personagem':'Nome do produto'}/></label><label className="field"><span>{memoryKind==='character'?'Rosto, cabelo, estilo e características':'Categoria, cor, textura e regras'}</span><textarea rows={5} maxLength={6000} value={memoryDetails} onChange={e=>setMemoryDetails(e.target.value)} placeholder="Seja específico sobre o que precisa ser preservado…"/></label><button className="primary-button" disabled={!!busy||!memoryName.trim()||!memoryDetails.trim()} onClick={()=>void saveMemory()}><Save size={16}/>Salvar referência</button></>:modal==='help'?<div className="help-steps"><div><b>01</b><span><h3>Comece pela referência</h3><p>Envie uma imagem ou descreva seu sujeito e cenário.</p></span></div><div><b>02</b><span><h3>Dê sua direção</h3><p>Escolha o objetivo, formato, câmera, iluminação e ação.</p></span></div><div><b>03</b><span><h3>Leve a ideia adiante</h3><p>Monte, revise e copie seu prompt. Salve o projeto para continuar depois.</p></span></div><p className="fine-print">O estúdio compõe textos por modelos. A criação de imagens e vídeos acontece na ferramenta de destino.</p></div>:<div className="plans">{[['Free','Primeiros projetos e composição básica'],['Creator','Mais gerações e biblioteca ampliada'],['Pro','Análise avançada e memórias'],['Agency','Equipes, clientes e projetos compartilhados']].map(([n,d])=><div key={n}><h3>{n}</h3><p>{d}</p><span>Planejado</span></div>)}</div>}</DialogContent></Dialog>
 </SidebarProvider>
}
