export type Config = { name:string; objective:string; description:string; action:string; camera:string; lighting:string; style:string; ratio:string; language:string; preserve:boolean; memory:string };
export const initialConfig:Config = {name:'',objective:'Vídeo Veo',description:'',action:'Movimento suave, natural e contínuo',camera:'50 mm · altura dos olhos',lighting:'Luz natural suave',style:'Ultrarrealista',ratio:'9:16',language:'English',preserve:true,memory:''};
export const objectives=['Vídeo Veo','TikTok Shop','Foto Instagram','Produto','Personagem','Cinema'];
export const templates=[
{id:'ugc',name:'UGC que conecta',category:'TikTok Shop',description:'Apresentação natural de produto, com foco nos detalhes.',icon:'shopping',config:{objective:'TikTok Shop',action:'Uma pessoa demonstra o produto com as mãos em uma única cena contínua de 8 segundos. Movimentos delicados. Sem texto na tela.',camera:'iPhone · enquadramento próximo',lighting:'Luz natural suave',style:'UGC natural',ratio:'9:16'}},
{id:'cinema',name:'Olhar cinematográfico',category:'Cinema',description:'Luz dramática, profundidade e movimentos precisos.',icon:'film',config:{objective:'Cinema',action:'A câmera se aproxima lentamente do sujeito em uma tomada contínua.',camera:'35 mm · travelling suave',lighting:'Luz lateral cinematográfica',style:'Cinematográfico',ratio:'16:9'}},
{id:'product',name:'Produto em destaque',category:'Produto',description:'Texturas fiéis e composição de catálogo premium.',icon:'box',config:{objective:'Produto',action:'Produto centralizado, fotografado de frente sobre uma superfície limpa.',camera:'85 mm · close nos detalhes',lighting:'Estúdio difuso',style:'Fotografia editorial',ratio:'1:1'}},
{id:'character',name:'Identidade consistente',category:'Personagem',description:'Características fixas para uma nova cena.',icon:'person',config:{objective:'Personagem',action:'Personagem em postura natural, olhando para a câmera.',camera:'50 mm · altura dos olhos',lighting:'Luz natural suave',style:'Ultrarrealista',ratio:'9:16'}}
];
export function composePrompt(c:Config,hasReference=false){
 const en=c.language==='English';
 const translate=(s:string)=>({'Luz natural suave':'Soft natural light','Luz lateral cinematográfica':'Cinematic side lighting','Estúdio difuso':'Diffused studio lighting','Golden hour':'Golden hour','50 mm · altura dos olhos':'50 mm lens, eye-level angle','35 mm · travelling suave':'35 mm lens, smooth tracking shot','85 mm · close nos detalhes':'85 mm lens, detailed close-up','iPhone · enquadramento próximo':'iPhone camera, close framing','Ultrarrealista':'Photorealistic','Cinematográfico':'Cinematic','UGC natural':'Natural UGC','Fotografia editorial':'Editorial photography','Movimento suave, natural e contínuo':'Smooth, natural, continuous movement'} as Record<string,string>)[s]||s;
 const val=(s:string)=>en?translate(s):s;
 const subject=c.description.trim();
 const ref=hasReference?(en?'Use the attached reference image for visual guidance.':'Use a imagem de referência anexada como guia visual.'):'';
 const lock=c.preserve?(en?'Preserve the identity, proportions, colors, materials and all visible design details of the reference. Do not invent hidden details.':'Preserve identidade, proporções, cores, materiais e todos os detalhes visíveis da referência. Não invente detalhes ocultos.'):'';
 const prompt=en?`Create a ${val(c.style).toLowerCase()} ${['Produto','Foto Instagram','Personagem'].includes(c.objective)?'image':'video'} in ${c.ratio} aspect ratio for ${c.objective}.\n\nSUBJECT & SCENE\n${subject}\n${ref}\n\nACTION\n${val(c.action)}\n\nCAMERA\n${val(c.camera)}. Coherent framing and realistic perspective.\n\nLIGHTING & STYLE\n${val(c.lighting)}. ${val(c.style)}. Natural textures, balanced exposure and professional composition.\n\nCONTINUITY\n${lock}\n${c.memory?`Saved reference instructions: ${c.memory}`:''}`:`Crie ${['Produto','Foto Instagram','Personagem'].includes(c.objective)?'uma imagem':'um vídeo'} em estilo ${c.style.toLowerCase()}, formato ${c.ratio}, para ${c.objective}.\n\nSUJEITO E CENÁRIO\n${subject}\n${ref}\n\nAÇÃO\n${c.action}\n\nCÂMERA\n${c.camera}. Enquadramento coerente e perspectiva realista.\n\nILUMINAÇÃO E ESTILO\n${c.lighting}. ${c.style}. Texturas naturais, exposição equilibrada e composição profissional.\n\nCONTINUIDADE\n${lock}\n${c.memory?`Referência salva: ${c.memory}`:''}`;
 return {prompt:prompt.trim(),negative:en?'No distorted anatomy, extra fingers, duplicate objects, morphing, illegible labels, watermarks or unwanted on-screen text. No abrupt camera motion.':'Sem anatomia distorcida, dedos extras, objetos duplicados, morphing, rótulos ilegíveis, marcas d’água ou texto indesejado na tela. Sem movimentos bruscos.',script:c.objective==='TikTok Shop'?'0–2 s: apresente o produto em enquadramento próximo.\n2–6 s: demonstre um detalhe visível, mantendo o produto fiel à referência.\n6–8 s: finalize com o produto em destaque. Adicione uma fala verdadeira e compatível com o anúncio.':''};
}
